"""Initial migration

Revision ID: a876ee7bae00
Revises: 
Create Date: 2025-09-03 22:03:10.148638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a876ee7bae00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('student_ID', sa.Integer(), nullable=True),
    sa.Column('admin_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_ID'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['student_ID'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissionDocument',
    sa.Column('submission_ID', sa.Integer(), nullable=False),
    sa.Column('document_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_ID'], ['document.id'], ),
    sa.ForeignKeyConstraint(['submission_ID'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('submission_ID', 'document_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissionDocument')
    op.drop_table('submission')
    op.drop_table('student')
    op.drop_table('document')
    op.drop_table('admin')
    # ### end Alembic commands ###
